mode_path: 'model/model.bin'

data:
  raw_data: '[CLS]态势感知'
  num_pieces: 100       #语料分多少分
  raw_dir: 'data/raw'
  raw: True
  train_dir: 'data/train'
  stride: 768

tokenizer:
  tokenizer_path: 'model/final_model/vocab.txt'

model:
  model_path: 'model/final_model'
  model_config: 'model/final_model/config.json'
train:
  batch_size: 2
  max_grad_norm: 1.0
  epoch: 32
  optimizer: 'adam'
  adam: 0.001
  lr_final: 0.0001

out:
  temperature: 1
  topk: 8   #最高几选一
  topp: 0     #最高积累概率
  length: 50
  fast_pattern: False
  repetition_penalty: 1.0
  
outputs:
  store: True
  output_dir: 'outputs'
  save_samples_path: 'outputs/samples'